### ISSUE TITLE
mac verify failure

### ISSUE THREAD

**Issue by shoutleafy** [tvrcgo/weixin-pay#14]
在createUnifiedOrder方法中，callback返回err:
Error: mac verify failure
    at Error (native)
    at Object.createSecureContext (_tls_common.js:135:17)
    at Object.exports.connect (_tls_wrap.js:997:48)
    at Agent.createConnection (https.js:82:22)
    at Agent.createSocket (_http_agent.js:182:26)
    at Agent.addRequest (_http_agent.js:144:10)
    at new ClientRequest (_http_client.js:158:16)
    at Object.exports.request (http.js:31:10)
    at Object.exports.request (https.js:199:15)
    at Request.start (/node/**_/node_modules/request/request.js:740:32)
    at Request.write (/node/**_/node_modules/request/request.js:1380:10)
    at end (/node/***_/node_modules/request/request.js:552:18)
    at Immediate._onImmediate (/node/**_/node_modules/request/request.js:581:7)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback](timers.js:523:5)

**Comment by iamdanielyin** [comment]
这个解决了吗，我也遇到同样的错误

**Comment by iamdanielyin** [comment]
我解决了，我是商户号错了
