### ISSUE TITLE
这个项目现在还能用吗？

### ISSUE THREAD

**Issue by cos800** [tvrcgo/weixin-pay#32]
我的代码是这样：
```js
        wxpay.createUnifiedOrder(orderInfo, (err,rst)=>{
            console.log(err);
            console.log(rst);
        });
```
然后输出错误：
```
TypeError: Cannot read property 'toString' of undefined
    at Parser.exports.Parser.Parser.parseString (/Users/cos800/projxxx/node_modules/xml2js/lib/xml2js.js:497:18)
    at Parser.parseString (/Users/cos800/projxxx/node_modules/xml2js/lib/xml2js.js:7:59)
    at Object.exports.parseXML (/Users/cos800/projxxx/node_modules/weixin-pay/lib/util.js:11:9)
    at Request._callback (/Users/cos800/projxxx/node_modules/weixin-pay/lib/wxpay.js:75:8)
    at self.callback (/Users/cos800/projxxx/node_modules/request/request.js:188:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.start (/Users/cos800/projxxx/node_modules/request/request.js:757:10)
    at Request.write (/Users/cos800/projxxx/node_modules/request/request.js:1511:10)
    at end (/Users/cos800/projxxx/node_modules/request/request.js:552:18)
    at Immediate.<anonymous> (/Users/cos800/projxxx/node_modules/request/request.js:581:7)
    at runCallback (timers.js:570:20)
    at tryOnImmediate (timers.js:550:5)
    at processImmediate [as _immediateCallback] (timers.js:529:5)
undefined
```

**Comment by cos800** [comment]
我是在`thinkjs`框架里使用`weixin-pay`来着~

**Comment by LincolnBurrows** [comment]
统一下单接口没问题，应该是你的orderInfo配置的有问题吧

**Comment by cos800** [comment]
应该是的，但是这个错误提示真让人无从下手啊。

**Comment by LincolnBurrows** [comment]
把orderInfo贴上来

**Comment by cos800** [comment]
我已经改用 wechat-pay https://github.com/supersheep/wechat-pay
算是解决了~
